-- MySQL Script generated by MySQL Workbench
-- 04/02/18 22:49:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema WebDiP2017x010
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2017x010
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2017x010` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2017x010` ;

-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`tip_korisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`tip_korisnika` (
  `tip_korisnika_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tip_korisnika_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`korisnici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`korisnici` (
  `korisnik_id` INT NOT NULL,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `adresa` VARCHAR(45) NULL,
  `grad` VARCHAR(45) NULL,
  `datum_pristupanja` DATETIME NOT NULL,
  `datum_zabrane` DATETIME NOT NULL,
  `broj_zabrana` INT NULL,
  `tip_korisnika_id` INT NOT NULL,
  PRIMARY KEY (`korisnik_id`),
  INDEX `tip_korisnika_id_idx` (`tip_korisnika_id` ASC),
  CONSTRAINT `tip_korisnika_id`
    FOREIGN KEY (`tip_korisnika_id`)
    REFERENCES `WebDiP2017x010`.`tip_korisnika` (`tip_korisnika_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`dnevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`dnevnik` (
  `dnevnik_id` INT NOT NULL,
  `dnevnik_korisnik` VARCHAR(45) NOT NULL,
  `dnevnik_adresa` VARCHAR(45) NOT NULL,
  `dnevnik_skripta` VARCHAR(255) NOT NULL,
  `dnevnik_preglednik` VARCHAR(255) NOT NULL,
  `dnevnik_vrijeme` TIMESTAMP NOT NULL,
  PRIMARY KEY (`dnevnik_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`kategorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`kategorija` (
  `kategorija_id` INT NOT NULL,
  `kategorija` VARCHAR(45) NOT NULL,
  `korisnik_id` INT NOT NULL,
  PRIMARY KEY (`kategorija_id`),
  INDEX `kategorija_korisnici_id_idx` (`korisnik_id` ASC),
  CONSTRAINT `kategorija_korisnici_id`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`moderira`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`moderira` (
  `korisnik_id` INT NOT NULL,
  `kategorija_kategorija_id` INT NOT NULL,
  PRIMARY KEY (`korisnik_id`),
  INDEX `fk_moderira_kategorija1_idx` (`kategorija_kategorija_id` ASC),
  CONSTRAINT `korisnik_id`
    FOREIGN KEY (`korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moderira_kategorija1`
    FOREIGN KEY (`kategorija_kategorija_id`)
    REFERENCES `WebDiP2017x010`.`kategorija` (`kategorija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`pitanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`pitanja` (
  `pitanja_id` INT NOT NULL,
  `tekst` VARCHAR(200) NOT NULL,
  `tocan_odgovor` VARCHAR(45) NOT NULL,
  `kategorija_id` INT NOT NULL,
  `kategorija_kategorija_id` INT NOT NULL,
  PRIMARY KEY (`pitanja_id`),
  INDEX `fk_pitanja_kategorija1_idx` (`kategorija_kategorija_id` ASC),
  CONSTRAINT `fk_pitanja_kategorija1`
    FOREIGN KEY (`kategorija_kategorija_id`)
    REFERENCES `WebDiP2017x010`.`kategorija` (`kategorija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`status_natjecanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`status_natjecanja` (
  `status_natjecanja_id` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`status_natjecanja_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`natjecanja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`natjecanja` (
  `natjecanja_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `datum_pocetka` DATETIME NOT NULL,
  `datum_kraja` DATETIME NOT NULL,
  `maksimalno_korisnika` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `kategorija_id` INT NOT NULL,
  `status_natjecanja_id` INT NOT NULL,
  `kategorija_kategorija_id` INT NOT NULL,
  `status_natjecanja_status_natjecanja_id` INT NOT NULL,
  PRIMARY KEY (`natjecanja_id`),
  INDEX `fk_natjecanja_kategorija1_idx` (`kategorija_kategorija_id` ASC),
  INDEX `fk_natjecanja_status_natjecanja1_idx` (`status_natjecanja_status_natjecanja_id` ASC),
  CONSTRAINT `fk_natjecanja_kategorija1`
    FOREIGN KEY (`kategorija_kategorija_id`)
    REFERENCES `WebDiP2017x010`.`kategorija` (`kategorija_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_natjecanja_status_natjecanja1`
    FOREIGN KEY (`status_natjecanja_status_natjecanja_id`)
    REFERENCES `WebDiP2017x010`.`status_natjecanja` (`status_natjecanja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`pitanja_na_natjecanju`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`pitanja_na_natjecanju` (
  `pitanja_id` INT NOT NULL,
  `natjecanja_id` INT NOT NULL,
  `natjecanja_natjecanja_id` INT NOT NULL,
  `pitanja_pitanja_id` INT NOT NULL,
  PRIMARY KEY (`pitanja_id`, `natjecanja_id`),
  INDEX `fk_pitanja_na_natjecanju_natjecanja1_idx` (`natjecanja_natjecanja_id` ASC),
  INDEX `fk_pitanja_na_natjecanju_pitanja1_idx` (`pitanja_pitanja_id` ASC),
  CONSTRAINT `fk_pitanja_na_natjecanju_natjecanja1`
    FOREIGN KEY (`natjecanja_natjecanja_id`)
    REFERENCES `WebDiP2017x010`.`natjecanja` (`natjecanja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pitanja_na_natjecanju_pitanja1`
    FOREIGN KEY (`pitanja_pitanja_id`)
    REFERENCES `WebDiP2017x010`.`pitanja` (`pitanja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`sudjelovanja_na_natjecanjima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`sudjelovanja_na_natjecanjima` (
  `sudjelovanja_na_natjecanjima_id` INT NOT NULL,
  `nadimak` VARCHAR(45) NOT NULL,
  `vrijeme_pocetka` DATETIME NOT NULL,
  `vrijeme_zavrsetka` DATETIME NOT NULL,
  `postotak_rjesenosti` FLOAT NOT NULL,
  `natjecanja_id` INT NOT NULL,
  `rezultat` INT NOT NULL,
  `natjecanja_natjecanja_id` INT NOT NULL,
  PRIMARY KEY (`sudjelovanja_na_natjecanjima_id`),
  UNIQUE INDEX `nadimak_UNIQUE` (`nadimak` ASC),
  INDEX `fk_sudjelovanja_na_natjecanjima_natjecanja1_idx` (`natjecanja_natjecanja_id` ASC),
  CONSTRAINT `fk_sudjelovanja_na_natjecanjima_natjecanja1`
    FOREIGN KEY (`natjecanja_natjecanja_id`)
    REFERENCES `WebDiP2017x010`.`natjecanja` (`natjecanja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`oglasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`oglasi` (
  `oglasi_id` INT NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NULL,
  `vrijeme_aktivnosti` DATETIME NULL,
  `vrsta_oglasa_id` INT NULL,
  `korisnik_id` INT NULL,
  `korisnici_korisnik_id` INT NOT NULL,
  PRIMARY KEY (`oglasi_id`),
  INDEX `fk_oglasi_korisnici1_idx` (`korisnici_korisnik_id` ASC),
  CONSTRAINT `fk_oglasi_korisnici1`
    FOREIGN KEY (`korisnici_korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`zahtjevi_za_oglasavanje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`zahtjevi_za_oglasavanje` (
  `oglasi_id` INT NOT NULL,
  `korisnik_id` INT NOT NULL,
  `prihvaceno` TINYINT(1) NULL,
  `oglasi_oglasi_id` INT NOT NULL,
  `korisnici_korisnik_id` INT NOT NULL,
  PRIMARY KEY (`oglasi_id`, `korisnik_id`),
  INDEX `fk_zahtjevi_za_oglasavanje_oglasi1_idx` (`oglasi_oglasi_id` ASC),
  INDEX `fk_zahtjevi_za_oglasavanje_korisnici1_idx` (`korisnici_korisnik_id` ASC),
  CONSTRAINT `fk_zahtjevi_za_oglasavanje_oglasi1`
    FOREIGN KEY (`oglasi_oglasi_id`)
    REFERENCES `WebDiP2017x010`.`oglasi` (`oglasi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjevi_za_oglasavanje_korisnici1`
    FOREIGN KEY (`korisnici_korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`zahtjevi_za_blokiranje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`zahtjevi_za_blokiranje` (
  `blokirano` TINYINT(1) NOT NULL,
  `korisnici_korisnik_id` INT NOT NULL,
  `oglasi_oglasi_id` INT NOT NULL,
  PRIMARY KEY (`blokirano`),
  INDEX `fk_zahtjevi_za_blokiranje_korisnici1_idx` (`korisnici_korisnik_id` ASC),
  INDEX `fk_zahtjevi_za_blokiranje_oglasi1_idx` (`oglasi_oglasi_id` ASC),
  CONSTRAINT `fk_zahtjevi_za_blokiranje_korisnici1`
    FOREIGN KEY (`korisnici_korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjevi_za_blokiranje_oglasi1`
    FOREIGN KEY (`oglasi_oglasi_id`)
    REFERENCES `WebDiP2017x010`.`oglasi` (`oglasi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`pozicija_prikaza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`pozicija_prikaza` (
  `id` INT NOT NULL,
  `stranica` INT NULL,
  `broj_lokacija` INT NULL,
  `sirina_oglasa` DECIMAL NULL,
  `visina_oglasa` DECIMAL NULL,
  `korisnici_korisnik_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pozicija_prikaza_korisnici1_idx` (`korisnici_korisnik_id` ASC),
  CONSTRAINT `fk_pozicija_prikaza_korisnici1`
    FOREIGN KEY (`korisnici_korisnik_id`)
    REFERENCES `WebDiP2017x010`.`korisnici` (`korisnik_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2017x010`.`vrste_oglasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2017x010`.`vrste_oglasa` (
  `id` INT NOT NULL,
  `trajanje` DATETIME NULL,
  `brzina_izmjene` TIME NULL,
  `cijena` DECIMAL NULL,
  `pozicija_prikaza_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vrste_oglasa_pozicija_prikaza1_idx` (`pozicija_prikaza_id` ASC),
  CONSTRAINT `fk_vrste_oglasa_pozicija_prikaza1`
    FOREIGN KEY (`pozicija_prikaza_id`)
    REFERENCES `WebDiP2017x010`.`pozicija_prikaza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
